GROUP=uk.co.fractalmotion.mugshot
VERSION_NAME=3.1.1-SNAPSHOT

POM_URL=https://github.com/TRazDev/Mugshot/
POM_SCM_URL=https://github.com/TRazDev/Mugshot/
POM_SCM_CONNECTION=scm:git:git://github.com/TRazDev/Mugshot.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/TRazDev/Mugshot.git

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=fractalmotion
POM_DEVELOPER_NAME=Fractal Motion
POM_DEVELOPER_URL=https://github.com/TRazDev/

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=false

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g

# Some submodules use newer SDK levels for testing.
android.suppressUnsupportedCompileSdk=UpsideDownCakePrivacySandbox

# Signals to our own plugin that we are building within the repo.
uk.co.fractalmotion.mugshot.internal=true

# Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Enabled configuration cache
org.gradle.configuration-cache=true
