package uk.co.fractalmotion.mugshot.sample.preview

import org.junit.Rule
import org.junit.Test
import uk.co.fractalmotion.mugshot.DeviceConfig
import uk.co.fractalmotion.mugshot.Mugshot
import uk.co.fractalmotion.mugshot.sample.mugshotPreviews

/**
 * Renders every `@Mugshot` preview in the module.
 *
 * `mugshotPreviews` is generated by `mugshot-preview-processor` from the `@Mugshot @Preview`
 * composables in main, so this test is the end to end proof that the preview pipeline works — and,
 * because it renders each screen's canonical preview, it doubles as the light mode baseline that
 * the variant tests below measure themselves against.
 *
 * It is a single `@Test` rather than a parameterised one on purpose: `MugshotPreviewData` is a data
 * class holding a lambda, so using it as a `@TestParameter` value would derive golden filenames
 * from a `Function0` identity hash and they would change on every run.
 */
class GeneratedPreviewSnapshotTest {
  @get:Rule val mugshot = Mugshot(deviceConfig = DeviceConfig.PIXEL_6)

  @Test
  fun preview() {
    mugshotPreviews.forEach { preview ->
      mugshot.snapshot(name = preview.snapshotName) { preview.composable() }
    }
  }
}
