package uk.co.fractalmotion.mugshot.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the JUnit test that renders every `@Mugshot` preview in the module.
 *
 * The file is a fixed template — only the package varies — because the preview catalogue itself is
 * generated by the KSP processor into the main source set. That keeps this task free of any
 * dependency on the processor's output, so it never has to wait for KSP or parse its results.
 *
 * The package must match the module namespace: `mugshotPreviewCases` is `internal`, and the unit
 * test compilation is a friend of main, so the generated test can read it only from the same
 * package.
 */
@CacheableTask
public abstract class GeneratePreviewTestTask : DefaultTask() {
  @get:Input
  public abstract val packageName: Property<String>

  @get:OutputDirectory
  public abstract val outputDirectory: DirectoryProperty

  @TaskAction
  public fun writeTest() {
    val packageName = packageName.get()
    val outputDir = outputDirectory.get().asFile
    outputDir.deleteRecursively()

    val sourceDir = outputDir.resolve(packageName.replace('.', '/'))
    sourceDir.mkdirs()
    sourceDir.resolve("$TEST_CLASS_NAME.kt").writeText(testSource(packageName))
  }

  private fun testSource(packageName: String): String =
    """
    package $packageName

    import org.junit.Rule
    import org.junit.Test
    import org.junit.runner.RunWith
    import org.junit.runners.Parameterized
    import uk.co.fractalmotion.mugshot.Mugshot
    import uk.co.fractalmotion.mugshot.preview.junit.newMugshot
    import uk.co.fractalmotion.mugshot.preview.runtime.MugshotPreviewCase

    /**
     * Generated by the Mugshot Gradle plugin. Do not edit.
     *
     * Renders every `@Mugshot` annotated `@Preview` in this module, once per configuration its
     * annotations ask for.
     */
    @RunWith(Parameterized::class)
    public class $TEST_CLASS_NAME(private val case: MugshotPreviewCase) {
      @get:Rule
      public val mugshot: Mugshot = case.config.newMugshot()

      @Test
      public fun snapshot() {
        val frames = case.frames()
        if (frames.size == 1) {
          mugshot.snapshot { frames.single()() }
        } else {
          // A @PreviewParameter preview: one image per value, indexed because a value's toString
          // is not safe in a filename.
          frames.forEachIndexed { index, frame -> mugshot.snapshot(name = "${'$'}index") { frame() } }
        }
      }

      public companion object {
        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        public fun cases(): List<Array<Any>> = mugshotPreviewCases.map { arrayOf<Any>(it) }
      }
    }

    """.trimIndent()

  internal companion object {
    const val TEST_CLASS_NAME: String = "MugshotGeneratedPreviewTest"
  }
}
